let feedbacksL = document.querySelector(".feedbacksL");
avioCompany.feedbacks.forEach(fb=>{
	let div1 = document.createElement("div");
	div1.classList.add("feedback-items");
	let div2 = document.createElement("div");
	div2.classList.add("comment-container");
	let p1 = document.createElement("p");
	p1.classList.add("comment");
	p1.innerHTML=fb.comment;
	div2.appendChild(p1);
	div1.appendChild(div2);
	let p2 = document.createElement("p");
	p2.classList.add("rate");
	p2.innerHTML=`Rating: ${fb.rate}`;
	div1.appendChild(p2);
	let p3 = document.createElement("p");
	p3.classList.add("date");
	p3.innerHTML=`Date: ${fb.date}`;
	div1.appendChild(p3);
	let p4 = document.createElement("p");
	p4.classList.add("user");
	p4.innerHTML=`User: ${fb.passenger.email}`;
	div1.appendChild(p4);
	feedbackList.appendChild(div1);
});